FROM arm32v6/alpine
COPY tmp/qemu-arm-static /usr/bin/qemu-arm-static

MAINTAINER Raymond Mouthaan <raymondmmouthaan@gmail.com>

ENV MOSQUITTO_VERSION 1.4.15-r3

RUN apk update && apk upgrade
RUN apk add mosquitto
RUN mkdir -p /mosquitto/config /mosquitto/data /mosquitto/log && chown mosquitto:mosquitto /mosquitto/*

COPY config /mosquitto/config
VOLUME ["/mosquitto"]

EXPOSE 1883 9001
CMD /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
